version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build: ./docker/php7
        #image: nandueverurs/php7-alphine-mysql-pdo (missing gd)
        container_name: PHP
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    mariadb:
        container_name: DB
        image: mariadb
        ports:
            - 4306:3306
        restart: always
        environment:
            MYSQL_DATABASE: dating_app
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/data:/var/lib/mysql